# Generated by Django 5.0.4 on 2024-04-11 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='code',
        ),
    ]
