# Generated by Django 5.0.4 on 2024-05-08 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0002_remove_language_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'Language', 'verbose_name_plural': 'Languages'},
        ),
        migrations.AlterModelTable(
            name='language',
            table='languages',
        ),
    ]
