# Generated by Django 5.0.4 on 2024-04-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0002_remove_translation_word'),
        ('word', '0003_remove_word_dictionary'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='translations',
            field=models.ManyToManyField(related_name='translations', to='translation.translation'),
        ),
    ]
