# Generated by Django 5.0.4 on 2024-05-08 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0004_word_translations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'verbose_name': 'Word', 'verbose_name_plural': 'Words'},
        ),
        migrations.AlterModelTable(
            name='word',
            table='words',
        ),
    ]
