# Generated by Django 5.0.4 on 2024-05-08 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_dictionary_words'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dictionary',
            options={'verbose_name': 'Dictionary', 'verbose_name_plural': 'Dictionaries'},
        ),
        migrations.AlterModelTable(
            name='dictionary',
            table='dictionaries',
        ),
    ]
