# Generated by Django 5.0.4 on 2024-04-11 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('word', '0002_word_dictionary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='word.word')),
            ],
        ),
    ]
