# Generated by Django 5.0.4 on 2024-04-11 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translation',
            name='word',
        ),
    ]
