# Generated by Django 5.0.4 on 2024-04-11 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0002_remove_translation_word'),
        ('word', '0004_word_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='source_word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='word.word'),
        ),
    ]
