# Generated by Django 5.0.4 on 2024-04-11 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0002_remove_language_code'),
        ('translation', '0003_translation_source_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='target_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='language.language'),
        ),
    ]
