# Generated by Django 5.0.4 on 2024-05-08 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0004_translation_target_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='translation',
            options={'verbose_name': 'Translation', 'verbose_name_plural': 'Translations'},
        ),
        migrations.AlterModelTable(
            name='translation',
            table='translations',
        ),
    ]
